function projectRoot = setupPaths()
%SETUPPATHS Add all SIH_Indian_AV source folders to the MATLAB path.
%
%   COMPONENT STATUS: REAL
%
%   projectRoot = SETUPPATHS() adds every source folder of this project to
%   the MATLAB search path and returns the absolute path of the project
%   root. Call this once at the start of any session:
%
%       >> setupPaths;
%
%   Portability note: the root is derived from the location of THIS file, so
%   the project works from any folder on any machine. No absolute path and
%   no username is hard-coded anywhere in this project.
%
%   Outputs:
%       projectRoot - char, absolute path to the folder containing this file
%
%   Requires: base MATLAB only.

projectRoot = fileparts(mfilename('fullpath'));

subDirs = { ...
    'config', 'utils', ...
    'planner', ...
    fullfile('planner','IR_PSC'), ...
    fullfile('planner','IR_PSC','corridor'), ...
    fullfile('planner','IR_PSC','risk'), ...
    fullfile('planner','IR_PSC','deformation'), ...
    fullfile('planner','IR_PSC','safety'), ...
    fullfile('planner','IR_PSC','trajectory'), ...
    fullfile('planner','baseline'), ...
    'prediction', ...
    fullfile('prediction','baseline'), ...
    fullfile('prediction','uncertainty'), ...
    fullfile('prediction','irregular_motion'), ...
    'perception', ...
    fullfile('perception','detection'), ...
    fullfile('perception','tracking'), ...
    fullfile('perception','fusion'), ...
    'sensors', ...
    fullfile('sensors','camera'), ...
    fullfile('sensors','lidar'), ...
    fullfile('sensors','radar'), ...
    'decision', ...
    fullfile('vehicle','controller'), ...
    fullfile('vehicle','dynamics'), ...
    'metrics', 'visualization', 'scripts', 'experiments', ...
    'scenarios', ...
    fullfile('scenarios','village'), ...
    fullfile('scenarios','urban_intersection'), ...
    fullfile('scenarios','highway_merge'), ...
    fullfile('scenarios','market'), ...
    fullfile('scenarios','cattle_crossing'), ...
    fullfile('scenarios','demo'), ...
    fullfile('tests','unit'), ...
    fullfile('tests','integration'), ...
    fullfile('tests','scenario') };

nAdded = 0;
for k = 1:numel(subDirs)
    d = fullfile(projectRoot, subDirs{k});
    if exist(d, 'dir') == 7
        addpath(d);
        nAdded = nAdded + 1;
    end
end

fprintf('SIH_Indian_AV: added %d source folders to the path.\n', nAdded);
fprintf('Project root: %s\n', projectRoot);
end
